# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jordons Portfolio Site
email: hello@jordon.io
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my photography portfolio, where every image tells a unique story. I am a passionate photographer dedicated to capturing the beauty of the world through my lens. With a keen eye for detail and a love for the art of visual storytelling, I aim to evoke emotions and create lasting memories through my photographs.
  My portfolio showcases a diverse collection of moments frozen in time. From breathtaking landscapes to candid portraits, each image reflects my dedication to capturing the essence of the world around us. Whether it's the vibrant colors of a sunset, the intricate details of a cityscape, or the genuine expressions of people, I strive to convey the beauty and emotions that lie within every frame.
  Exploring the world with my camera has allowed me to discover the extraordinary in the ordinary, and I'm thrilled to share these moments with you. I believe that photography has the power to inspire, connect, and transcend boundaries. Through my work, I hope to take you on a visual journey and spark your own sense of wonder and curiosity.
  Thank you for visiting my portfolio. Feel free to explore the galleries and immerse yourself in the world of photography. If you have any questions, inquiries, or would like to collaborate, please don't hesitate to reach out. Your feedback and support mean the world to me, and I look forward to sharing more captivating moments with you.
baseurl: "/test-portfolio/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  photos:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
